extends Node

# Converts points to binary number
enum Figure {
	POPULUS, LAETITIA, RUBEUS, FORTUNA_MINOR,
	ALBUS, AMISSIO, CONJUNCTIO, CAUDA_DRACO,
	TRISTITIA, CARCER, ACQUISITIO, PUER,
	FORTUNA_MAJOR, PUELLA, CAPUT_DRACO, VIA
}

# Correspondences
enum Element { FIRE, AIR, WATER, EARTH }

enum Planet {
	SATURN, JUPITER, MARS, SUN, VENUS,
	MERCURY, MOON, NORTH_NODE, SOUTH_NODE
}

enum Zodiac {
	ARIES, TAURUS, GEMINI, CANCER,
	LEO, VIRGO, LIBRA, SCORPIO,
	SAGITTARIUS, CAPRICORN, AQUARIUS, PISCES
}

enum System { AGRIPPA, GERARDO }
